### ISSUE TITLE
How to Import this into my project, Maven Plugin Not Supported Current Build Tool Version

### ISSUE THREAD

**Issue by mohanrajsambath** [rhexgomez/typer#1]
i  Was tried to import the library as module in my project, at that moment have show this  Error:(2, 0) Plugin with id 'com.github.dcendents.android-maven' not found.
<a href="openFile:/Users/apple1//Clients/android/project/sms/Working Copy/SMS_wsp/typerlib/build.gradle">Open File</a>.
Please help me to update for my new android gradle version. Bring steps to import in my project.

**Comment by elmargomez** [comment]
Pls. show your **build.gradle** file.
