### ISSUE TITLE
How can we know if the font is applied and any global solution ?

### ISSUE THREAD

**Issue by kareemzok** [rhexgomez/typer#2]
How to know if the font is applied on the app and is there any solution to apply on all elements instead of calling it on each one ?

**Comment by rhexgomez** [comment]
I might consider adding a built-in `<style>` in which you can add directly to your app manifest 
e.g. 
```xml
<application
    android:theme="@style/TyperFontTheme" >
</application>
```
We'll see.

**Comment by kareemzok** [comment]
Would be great.
When it will be available? Coz I m kind in a hurry to finish implementing the font 

Thanks

**Comment by rhexgomez** [comment]
I am starting it now as experimental-branch and my my required `minSdkVersion` is **16**

**Comment by kareemzok** [comment]
Great then we will be waiting to try it soon! 
Let us know once its implemented!

**Comment by rhexgomez** [comment]
Disclaimer : The repository is updated but not the library version in Maven.

Hi I have updated the library and provided an example app in Kotlin (let me know if you prefer a Java example). 

Requirements  : 

- You need to use `AppCompatTextView` if you're using regular `TextView` and `AppCompatEditText` if your are using regular `EditText` this will ensure the font(s) will be rendered correctly.
- required `minSdkVersion` is **16**

Example code:
```xml
<application
        ...
        android:theme="@style/TyperLib.Theme.Roboto.{font name here}">

// Example

<application
       ... 
       android:theme="@style/TyperLib.Theme.Roboto.ThinItalic">
// or
<application
       ... 
       android:theme="@style/TyperLib.Theme.Roboto.Regular">
```

**Comment by kareemzok** [comment]
Hello, 
Thanks for the update but I m using the java code not kotlin.
Please if you can update with the java code. 

Also still I need to import the library locally ?

**Comment by rhexgomez** [comment]
Hi,
Sorry for the late reply so finally I manage providing a [Java example](https://github.com/rhexgomez/typer/tree/master/java_roboto_example) which is just importing the library locally. I already uploaded a new artifact in JCenter and waiting for the approval so that you can use it in your Gradle. 

![device-2019-02-20-220139](https://user-images.githubusercontent.com/12870294/53249147-65d5b280-36f2-11e9-8508-e9d501646873.png)

**Comment by kareemzok** [comment]
Great great thanks for your effort and waiting the approval.
To apply on my side i need to do sync of the gradle right to take the new updates ?

**Comment by rhexgomez** [comment]
Importing the library locally is a bit tedious (I personally do not like it) and right now I am still waiting for the approval, I have no idea why it takes too long. But once it is approved I will update the README with explanation.

**Comment by kareemzok** [comment]
Ohh okayy 
Thanks a lot for your effort and great work really! 
I should get the notification if you updated the readme file right ?? 
I m not hurry, we can wait for the approval

**Comment by rhexgomez** [comment]
Hi thanks for the patience waiting for this update I really appreciate it! I am not exactly sure if Github notifies after updating the README but I will post an update here in issuetracker just to be sure :)

**Comment by rhexgomez** [comment]
Hi the wait is over the library is now hosted in JCenter and the README is now updated, let me know if you have further questions! :D :tada: :tada:

**Comment by kareemzok** [comment]
Ahh great, i will apply it tonight and try. 
I have migrated my project to androidX so I m not sure if its still be working but will try that.

**Comment by rhexgomez** [comment]
I will now close this thread feel free to open a new thread.
